---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

# - name: Disable ipv6
#   shell: sed -i 's@\(GRUB_CMDLINE_LINUX=".*\)"@\1 ipv6.disable=1"@g' /etc/default/grub

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Europe/Kiev

- name: Enable ntp sync
  shell: timedatectl set-ntp true

# - name: Enable mirrors
#   shell: sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

# - name: Enable mirrors
#   shell: sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* 


- name: YUM install
  yum:
    name:
    - vim
    - tmux
    - bash-completion
    - net-tools
    - wget