---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Disable ipv6
  shell: sed -i 's@\(GRUB_CMDLINE_LINUX=".*\)"@\1 ipv6.disable=1"@g' /etc/defaul/grub

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Europe/Kiev

- name: Enable ntp sync
  shell: timedatectl set-ntp true

- name: Install the epel
  yum:
    name: yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: YUM install
  yum:
    name:
    - vim
    - tmux
    - bash-completion
    - net-tools
    - wget